pluginId=pano-plugin-slider
pluginName=Pano Slider Plugin
pluginDescription=Adds a customizable and responsive slider component to Pano themes.
pluginPanoVersion=local-build
pluginClass=com.panomc.plugins.slider.SliderPlugin
pluginDeveloper=Pano
pluginLicense=MIT
pluginSourceUrl=https://github.com/panomc/pano-plugin-slider
pluginDependencies=
pluginRequires=

pf4jVersion=3.11.1
vertxVersion=4.5.7
gsonVersion=2.11.0
handlebarsVersion=4.4.0
organization=panomc